# This is duplicated here from configs/mydoc/config_designers.yml so that Github Pages can read it. Github Pages requires this file for the build process. It can't read a configuration file stored in another location.

# project definitions
project: mydoc_designers
audience: designers
product: doc
platform: all
version: all
output: web
destination: ../doc_outputs/mydoc/designers
topnav_title: Documentation Page
homepage_title: Jekyll doc for angularjs backand
site_title: Jekyll theme for designers
project_folder: mydoc
company_name: Backand
footer_image_location: ../common_images/company_logo.png
github_editme_path: tomjohnson1492/documentation-theme-jekyll/edit/reviews
disqus_shortname: backand
# variables

sidebar_tagline: Back& Documentation
sidebar_version: version 1.8.x
theme_file: theme-blue.css
pdf_file_name: mydoc_designers_pdf.pdf
baseurl: /
port: 4009

exclude:
  - _site
  - _drafts
  - configs/
  - doc/mydoc_writers*

# same for all
host: 127.0.0.1
feedback_email: ygalbel@backand.com

markdown: kramdown

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: pygments

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

